apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test


resources:
- ../../base
- ./ns.yaml

patches:
- path: ./container_env.yaml
  target:
    kind: Deployment
- path: ./container_probe.yaml
  target:
    kind: Deployment
- path: ./container_lifecycle.yaml
  target:
    kind: Deployment
- path: ./container_resources.yaml
  target:
    kind: Deployment
